// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apxlmlzvzqcvigrsiqsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFweGxtbHp2enFjdmlncnNpcXNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMjQ4NjgsImV4cCI6MjA2MDcwMDg2OH0.eaOla5r-0cBEMRYtVtEfCgnlIJsB3zvDyBQI9r69XKY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);