// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urukpofengkdqkhlwntk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVydWtwb2ZlbmdrZHFraGx3bnRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMjIwMDEsImV4cCI6MjA2MDY5ODAwMX0.-iD7yIbAMZB4qkN_qZhCEHSOkpoDOtFx1UuJPP2ygLE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);